Vagrant.configure(2) do |config|
  config.vm.define 'chromedriver'
  config.vm.box = 'blueimp/chromedriver'
  #config.vm.box_url = 'file:////vistaprint.net/amsterdam/Share/Exchange%20Folder/Gusztav/vagrant/albumprinter--gv-windows10ee-default--0.4.0--virtualbox.box'

  config.vm.provider 'virtualbox' do |virtualbox|
    virtualbox.name = 'chromedriver.vagrant'
	virtualbox.gui = true
  end

  config.vm.network "private_network", ip: "172.16.43.115"
  config.vm.network :forwarded_port, guest: 3389, host: 63599, id: "rdp", auto_correct: true
end

