Vagrant.configure(2) do |config|
  config.vm.define 'windows10'
  config.vm.box = 'albumprinter/workstation-win10'
  config.vm.box_url = 'file:////vistaprint.net/amsterdam/Share/Exchange%20Folder/Gusztav/vagrant/albumprinter--gv-windows10ee-default--0.4.0--virtualbox.box'

  config.vm.provider 'virtualbox' do |virtualbox|
    virtualbox.name = 'windows10.vagrant'
  end

  config.vm.network "private_network", ip: "172.16.43.115"
  config.vm.network :forwarded_port, guest: 3389, host: 63189, id: "rdp", auto_correct: true
end

